[symlinks]
"/home/louis/.zshrc" = "/home/louis/code/dotfiles/zsh/zshrc"
"/home/louis/.gitconfig" = "/home/louis/code/dotfiles/git/gitconfig"
"/home/louis/.gitconfig.local" = "/home/louis/code/dotfiles/git/gitconfig.local"
"/home/louis/.config/i3/i3blocks.conf" = "/home/louis/code/dotfiles/i3/i3blocks.conf"
"/home/louis/Pictures/wallpaper/wallpaper_16x9.jpg" = "/home/louis/code/dotfiles/i3/wallpaper/wallpaper_16x9.jpg"
"/home/louis/.config/i3/i3-rofi-system-actions.sh" = "/home/louis/code/dotfiles/i3/rofi/i3-rofi-system-actions.sh"
"/home/louis/.config/tmux/tmux.conf" = "/home/louis/code/dotfiles/tmux/tmux.conf"
"/home/louis/.gitignore" = "/home/louis/code/dotfiles/git/gitignore"
"/home/louis/.config/compton.conf" = "/home/louis/code/dotfiles/i3/compton/compton.conf"
"/home/louis/.config/polybar/launch.sh" = "/home/louis/code/dotfiles/i3/polybar/launch.sh"
"/home/louis/.config/i3/config" = "/home/louis/code/dotfiles/i3/config"
"/home/louis/.config/rofi/config.rasi" = "/home/louis/code/dotfiles/i3/rofi/config.rasi"
"/home/louis/.config/rofi/my-theme.rasi" = "/home/louis/code/dotfiles/i3/rofi/my-theme.rasi"
"/home/louis/.config/wezterm" = "/home/louis/code/dotfiles/wezterm/config"
"/home/louis/.config/polybar/config.ini" = "/home/louis/code/dotfiles/i3/polybar/config.ini"
"/home/louis/.p10k.zsh" = "/home/louis/code/dotfiles/zsh/p10k/custom_config.zsh"
"/home/louis/.config/nvim" = "/home/louis/code/dotfiles/nvim/config"
